### ISSUE TITLE
Error: _ is not defined

### ISSUE THREAD

**Issue by francesharlow** [notzooey/beyonce-memory#1]
Hi Sung,

I'm sure there's a quick fix for this, but it's bogging me down at present. When I try to run my JS in the browser, I get an error message saying _ is not defined.

I downloaded the underscore.js library, and I believe I correctly linked to it in my HTML:

```
<script type="text/javascript" src="underscore.js"></script>
```

Notably, _.sample does work when I copy and paste my code into the console.

If you have a moment, could you please help? Thank you!

**Comment by sungchoi** [comment]
Hi Frances,

The order in which you load your code matters. That includes libraries like underscore and jQuery.
Ask yourself, when my sample method is run, has `_` been defined yet?

**Comment by sungchoi** [comment]
(Close this issue once you solve this. Or send me a follow question/thoughts)

**Comment by francesharlow** [comment]
That worked! Thanks, Sung!
