### ISSUE TITLE
JS Lint your code!

### ISSUE THREAD

**Issue by phlco** [notzooey/beyonce-memory#2]
Hiya! I just ran your code through http://www.jshint.com

It can give you some helpful warnings about things to correct

Here's the output with the line numbers and problems.  See if any of these help!

```
Five warnings
20  Missing semicolon.
26  Missing semicolon.
64  Unnecessary semicolon.
68  Don't make functions within a loop.
76  Missing semicolon.
Four unused variables
17  Card
22  cardDeck
74  takeTurn
96  addRow
```

**Comment by francesharlow** [comment]
Thanks, Phil! This was mega helpful.
