### ISSUE TITLE
Button Issues

### ISSUE THREAD

**Issue by francesharlow** [notzooey/beyonce-memory#3]
Hi Sung,

As a bonus, I'm trying to add a couple of event listeners, which will respectively reset my memory game and add an additional row of boxes. I can independently invoke the addRow function in the console, but when I use it as a callback for an eventListener, I get an error saying it's not a function. 

```
var addButton = document.querySelectorAll('#add');

var addRow = function(event){
  var allColumns = document.querySelectorAll('.column');
  // console.log(allColumns);
  for (var i = 0; i < allColumns.length; i ++) {
    var newRow = document.createElement('div');
    newRow.classList.add('card');
    newRowArray.push(newRow);
    allColumns[i].appendChild(newRowArray[i]);
  }
};

addButton.addEventListener('click',addRow);
```

Similarly, my Reset Button is successfully invoked with the eventListener, and it correctly pulls a new random sample of img each time that it's clicked, but when I iterate through the arrays, it doesn't assign the new imgs to the card divs. It uses the same ones that were pulled in the setUpBoard function that loads with the page.

```
var randomBeyonceSample;
var cardDeck;
var newCard;
var newCardArray = [];
var newRowArray = [];

var resetBoard = function(){
  // take a random sample of the imgs that is equal to half the total number of cards
  randomBeyonceSample = _.sample(beyonces,(allCards.length / 2));
  // create new array in which each item in the random sample appears exactly twice
  cardDeck = _.flatten([randomBeyonceSample,randomBeyonceSample]);
  //reshuffle the array
  _.shuffle(cardDeck);
  // iterate through the array, creating a new img for each item, giving each img a corresponding src, adding to it the class of hidden
  for (var i = 0; i < cardDeck.length; i ++){
    newCard = document.createElement('img');
    newCard.src = cardDeck[i];
    newCard.classList.add('hidden');
    // push the newly formed card to another array so it can be appended to each item in allCards
    newCardArray.push(newCard);
    console.log(newCardArray);
    // append each card, with its img, src, and class of hidden, to an existing card div 
    allCards[i].appendChild(newCardArray[i]);
    // console.log(allCards[0]);
    // add an event listener to each card so that, when clicked, it invokes takeTurn()
    allCards[i].addEventListener('click', takeTurn);
  }
};
```

Of course, there's no rush on this -- I know you're meeting 1-on-1 with a bunch of people today, so if you don't have time to get to this, it's absolutely not a problem. I'll just focus on sprucing up the CSS in the meantime. 

Thanks so much!

**Comment by sungchoi** [comment]
@francesharlow 

Can you send me the exact errors and error line numbers copied from the console?

**Comment by francesharlow** [comment]
Hi Sung! Sorry for the delay, and thanks for responding. I took a break from this yesterday but will get back to you if I find I have more questions moving forward.
